server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    loadbalancer:
      ribbon:
        # Added only for better readability
        enabled: false
    consul:
      enabled: true
      discovery: # Get only services that are passing the health check
        query-passing: true
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
default-filters:
  - name: Retry
    # In case the gateway fails to proxy a request to a service, we want it to retry a few times
    args:
      retries: 3
      methods: GET, POST
# route config
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace
